homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 43.071710
  longitude: -89.437207
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 273
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

#### ARLO SETUP ###
arlo:
  username: !secret arlo_username
  password: !secret arlo_password

camera:
  - platform: arlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

sensor:
  - platform: arlo
    monitored_conditions:
      - captured_today
      - last_capture
      - total_cameras
      - battery_level
###

### ECOBEE SETUP ###
ecobee:
  api_key: !secret ecobee_api_key
  hold_temp: false
###

### UNIFI DEVICE TRACKING ###
device_tracker:
  - platform: unifi
    host: 192.168.1.18
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: false
###

### WEATHERUNDERGROUNG SETUP ###
sensor 1:
  - platform: wunderground
  api_key: !secret wunderground_api_key
  monitored_conditions:
    - alerts
    - dewpoint_f
    - dewpoint_string
    - feelslike_f
    - feelslikestring
    - heat_index_f
    - heat_index_string
    - observation_time
    - precip_today_in
    - precip_today_string
    - precip_1d_in
    - precip_1d
    - pressure_in
    - pressure_trend
    - relative_humidity
    - solarradiation
    - temperature_string
    - temp_f
    - temp_high_record_f
    - temp_low_record_f
    - temp_high_avg_f
    - temp_low_avg_f
    - temp_high_1d_f
    - temp_low_1d_f
    - UV
    - visibility_mi
    - weather
    - weather_1d
    - weather_1h
    - wind_degrees
    - wind_dir
    - wind_gust_mph
    - wind_gust_1d_mph
    - wind_mph
    - wind_1d_mph
    - wind_string
###

### TP-Link Switches ###
switch:
  - platform: tplink
    name: Living Room Lamp
    host: IP_ADDRESS


switch 1:
  - platform: tplink
    name: Coffee Pot
    host: IP_ADDRESS


### Chromecasts ###
media_player:
  - platform: cast
    host: ###.###.###.###

media_player 1:
  - platform: cast
    host: ###.###.###.###



group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml