homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 43.071710
  longitude: -89.437207
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 273
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

#Show hassio menu
hassio:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
#map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

google_assistant:
  project_id: !secret ga_project_id
  client_id: !secret ga_client_id
  access_token: !secret ga_access_token
#  agent_user_id: !secret ga_agent_user_i
  api_key: !secret ga_api_key
  exposed_domains:
    - switch


#### ARLO SETUP ###
arlo:
  username: !secret arlo_username
  password: !secret arlo_password

camera:
  - platform: arlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

sensor:
  - platform: arlo
    monitored_conditions:
      - captured_today
      - last_capture
      - total_cameras
      - battery_level
###

### ECOBEE SETUP ###
ecobee:
  api_key: !secret ecobee_api_key
  hold_temp: false
###

### UNIFI DEVICE TRACKING ###
device_tracker:
  - platform: unifi
    host: !secret unifi_controllerip
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: false
    track_new_devices: false
###

### WEATHERUNDERGROUNG SETUP ###
sensor 1:
  - platform: wunderground
    api_key: !secret wunderground_api_key
    monitored_conditions:
      - temp_high_record_c
      - temp_high_1d_c
      - temp_c
      - temp_low_1d_c
      - temp_low_record_c
      - precip_1d
      - precip_1d_mm
      - wind_kph
      - wind_1d_kph
      - alerts
###

### TP-Link Switches ###
switch:
  - platform: tplink
    name: Living Room Lamp
    host: 192.168.1.200

switch 1:
  - platform: tplink
    name: Coffee Pot
    host: 192.168.1.201

switch 2:
  - platform: tplink
    name: Christmas Tree
    host: 192.168.1.199

### Chromecasts ###
media_player:
  - platform: cast
    name: Basement
    host: 192.168.1.204

media_player 1:
  - platform: cast
    name: Attic
    host: 192.168.1.205

#media_player_2:
#  - platform: cast
#    name: Home Mini - Kitchen
#    host: 192.168.1.203

#media_player_3:
#  - platform: cast
#    name: Home Mini - Living Room
#    host: 192.168.1.197

#media_player_4:
#  - platform: cast
#    name: Home Mini - Bano
#    host: 192.168.1.198

media_player 3:
  - platform: samsungtv
    name: Living Room TV
    host: 192.168.1.206
    mac: f8:3f:51:20:01:82

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml